<!doctype html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="stylesheet" type="text/css" media="all" href="bootstrap/css/bootstrap.css" />
        <script type="text/javascript" src="bootstrap/js/jquery.js" ></script>
        <script type="text/javascript" src="bootstrap/js/bootstrap.js" ></script> 

        <link href="css/estilo.css" rel="stylesheet" type="text/css" media="screen">
        <title>Nippes Estamparia</title>
    </head>

    <body>

        <header class="century">
            <nav>
                <figure class="fig">
                    <img class="logotipo" src="img/logo.png" width="100px" height="25px" /> <b class="font15px">| ESTAMPARIA </b>
                    <ul class="cabecalhotopo">
                        <li><a href="cadastro.html"> LOGIN | CRIE SUA CONTA</a></li>
                        <li><a>Facebook | Google </a></li>
                    </ul><br>
                </figure>			
                <ul class="cabecalho">
                    <li><a href="home.html" style="text-decoration:none"> HOME </a></li>
                    <li><a href="pedidos.html" style="text-decoration:none"> PEDIDOS</a></li>
                    <li><a href="catalogo.html" style="text-decoration:none"> CATÁLOGO</a></li>
                    <li><a href="faleconosco.html" style="text-decoration:none"> CONTATO</a></li>
                    <li class="margin-left40"><a href="cadastro.html" style="text-decoration:none"></a></li>					
                    <div class="padding10">
                        <input type="text"/>
                        <button>I</button>
                    </div>				
                    <img class="carrinho" src="img/carrinho2.png" width="30px"/>
                </ul>
            </nav>
            <header class="font33px margin-left40">
                <p>Filtro:</p>
            </header>
            <section class="min-width50 textcenter">
                <figure class="catalogovenda">
                    <img src="img/img1.png" title="Camisa"/>
                    <figcaption>
                        <p>
                            <a href="#">	Jazzman a partir de <b>R$64,90</b> </a>
                        </p>
                    </figcaption>
                </figure>
                <figure class="catalogovenda">
                    <img src="img/img2.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Music is the way a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>	
                <figure class="catalogovenda">
                    <img src="img/img3.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Dark Prince a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>	
                <figure class="catalogovenda">
                    <img src="img/img4.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Infinite Love a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>	
                <figure class="catalogovenda">
                    <img src="img/img5.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Am I Free Or Tield Up a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>		
                <figure class="catalogovenda">
                    <img src="img/img6.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Until The Very End a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>		
                <figure class="catalogovenda">
                    <img src="img/img7.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Winter is Coming a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>	
                <figure class="catalogovenda">
                    <img src="img/img8.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Tente outra vez a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>	
                <figure class="catalogovenda">
                    <img src="img/img2.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Tente outra vez a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>	
                <figure class="catalogovenda">
                    <img src="img/img1.png" title="Camisa" />
                    <figcaption>
                        <p>
                            <a href="#">Tente outra vez a partir de <b>R$64,90</b></a>
                        </p>
                    </figcaption>
                </figure>	
                <div class="botaovermais">
                    <input class="col-lg-6 col-md-6 col-sm-6 col-xs-6 btn btn-primary" type="submit" value="Ver Mais" data-toggle="tooltip" title="Clique aqui para ENTRAR" data-placement="bottom"/>
                </div>		
            </section>
            <footer class="rodape">
                <legend><p class="textcenter">© RUA MARIA GERMANI CEP: 18053030, Nº883 - JULIO DE MESQUITA TEL:(15)32025270 | E-MAIL: NIPPES@HOTMAIL.COM </p></legend>
                <figure class="textcenter">
                    <figcaption class="textcenter">CONECTE-SE</figcaption>
                    <img src="img/iconeeees.png" width="300px" height="75px" alt="icones"  class="textcenter" />
                </figure> <p class="textcenter"> Home | Catalogo | Pedidos | Login | Sobre Nós </p>
                <p class="textcenter gray"> © RUA MARIA GERMANI CEP: 18053030, Nº883 - JULIO DE MESQUITA TEL:(15)32025270 | E-MAIL: NIPPES@HOTMAIL.COM 
            </footer>
            <!--
            <footer class="telefone">
            © RUA MARIA GERMANI CEP: 18053030, Nº883 - JULIO DE MESQUITA
                                                                                                                                                                                    TEL:(15)32025270 |
            E-MAIL: NIPPES@HOTMAIL.COM
            </footer> -->
    </body>
</html>