<!doctype html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="stylesheet" type="text/css" media="all" href="bootstrap/css/bootstrap.css" />
        <script type="text/javascript" src="bootstrap/js/jquery.js" ></script>
        <script type="text/javascript" src="bootstrap/js/bootstrap.js" ></script> 

        <link href="css/estilo.css" rel="stylesheet" type="text/css" media="screen">
        <title>Nippes Estamparia</title>
    </head>

    <body>

        <header class="century">
            <nav>
                <figure class="fig">
                    <img class="logotipo" src="img/logo.png" width="100px" height="25px" /> <b class="font15px">| ESTAMPARIA </b>
                    <ul class="cabecalhotopo">
                        <li><a href="cadastro.html"> LOGIN | CRIE SUA CONTA</a></li>
                        <li><a>Facebook | Google </a></li>
                    </ul><br>
                </figure>			
                <ul class="cabecalho">
                    <li><a href="home.html" style="text-decoration:none"> HOME </a></li>
                    <li><a href="pedidos.html" style="text-decoration:none"> PEDIDOS</a></li>
                    <li><a href="catalogo.html" style="text-decoration:none"> CATÁLOGO</a></li>
                    <li><a href="faleconosco.html" style="text-decoration:none"> CONTATO</a></li>
                    <li class="margin-left40"><a href="cadastro.html" style="text-decoration:none"></a></li>					
                    <div class="padding10">
                        <input type="text"/>
                        <button>I</button>
                    </div>				
                    <img class="carrinho" src="img/carrinho2.png" width="30px"/>
                </ul>
            </nav>
            <TABLE class="tabela">

                <TR>

                    <TH>Produto</TH>

                    <TH>Quantidade </TH>

                    <TH>Total</TH>

                </TR>

                <TR>

                    <TD class="bolder">SEU CARRINHO ESTÁ VAZIO</TD>

                    <TD> </TD>

                    <TD> </TD>

                </TR>

            </TABLE>


















            <footer class="rodape">
                <legend><p class="textcenter">© RUA MARIA GERMANI CEP: 18053030, Nº883 - JULIO DE MESQUITA TEL:(15)32025270 | E-MAIL: NIPPES@HOTMAIL.COM </p></legend>
                <figure class="textcenter">
                    <figcaption class="textcenter">CONECTE-SE</figcaption>
                    <img src="img/iconeeees.png" width="300px" height="75px" alt="icones"  class="textcenter" />
                </figure> <p class="textcenter"> Home | Catalogo | Pedidos | Login | Sobre Nós </p>
                <p class="textcenter gray"> © RUA MARIA GERMANI CEP: 18053030, Nº883 - JULIO DE MESQUITA TEL:(15)32025270 | E-MAIL: NIPPES@HOTMAIL.COM 
            </footer>
            <!--
            <footer class="telefone">
            © RUA MARIA GERMANI CEP: 18053030, Nº883 - JULIO DE MESQUITA
                                                                                                                                                                                    TEL:(15)32025270 |
            E-MAIL: NIPPES@HOTMAIL.COM
            </footer> -->
    </body>
</html>